version: "3"
services:
  nest-api:
    container_name: clean-architecture-api
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:14.1
    restart: always
    container_name: clean-architecture-db
    ports:
      - 5432:5432
    env_file:
      - .env.development
    volumes: 
      - postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.4
    restart: always
    ports:
    - 8080:80
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - .env.development
    # environment:
    #   PGADMIN_DEFAULT_EMAIL: admin@admin.com
    #   PGADMIN_DEFAULT_PASSWORD: root

volumes:
  postgres:
    name: clean-architecture-db