export const DBConfiguration = {
  POSTGRES_USER: 'POSTGRES_USER',
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
  POSTGRES_DB: 'POSTGRES_DB',
  POSTGRES_HOST: 'POSTGRES_HOST',
  POSTGRES_PORT: 'POSTGRES_PORT',
  SERVER_PORT: 'SERVER_PORT',
};

export const AWSCloudWatchConfiguration = {
  CLOUDWATCH_GROUP_NAME: 'CLOUDWATCH_GROUP_NAME',
  CLOUDWATCH_STREAM_NAME: 'CLOUDWATCH_STREAM_NAME',
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
  AWS_REGION: 'AWS_REGION',
};

export const JWTConfiguration = {
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRATION_TIME: 'JWT_EXPIRATION_TIME',
  JWT_REFRESH_TOKEN_SECRET: 'JWT_REFRESH_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME: 'JWT_REFRESH_TOKEN_EXPIRATION_TIME',
};
