export const DBConfiguration = {
  POSTGRES_USER: 'POSTGRES_USER',
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
  POSTGRES_DB: 'POSTGRES_DB',
  POSTGRES_HOST: 'POSTGRES_HOST',
  POSTGRES_PORT: 'POSTGRES_PORT',
  SERVER_PORT: 'SERVER_PORT',
};

export const AWSCloudWatchConfiguration = {
  CLOUDWATCH_GROUP_NAME: 'CLOUDWATCH_GROUP_NAME',
  CLOUDWATCH_STREAM_NAME: 'CLOUDWATCH_STREAM_NAME',
  AWS_ACCESS_KEY: 'AWS_ACCESS_KEY',
  AWS_KEY_SECRET: 'AWS_KEY_SECRET',
  AWS_REGION: 'AWS_REGION',
};
